#pragma once

#define BUFFER_TIME_SIZE 10
#define IDS_PROBES_DEBUG

//#define IDS_LATENCY_BENCHMARK

#define IDS_P1_ENABLED
#define IDS_P2_ENABLED
#define IDS_P3_ENABLED
#define P3_PROFILING_ENABLED

#define LOGGING_P0_ENABLED
#define LOGGING_P1_ENABLED
#define LOGGING_P2_ENABLED
#define LOGGING_P3_ENABLED
//#define LOGGING_P3_BIS_ENABLED

#define IDS_TELEM_ENABLED
//#define IDS_TELEM_DEBUG
//#define CPU_BENCHMARK_TEST
#define CFDP_FLOOD_LIFT

//#define CPU_BENCHMARK
