[ubuntu_machines]
host1 ansible_host=192.168.100.11 ansible_user=nos3 ansible_ssh_pass=nos3123! ansible_become_pass=nos3123!
host2 ansible_host=192.168.100.12  ansible_user=nos3 ansible_ssh_pass=nos3123! ansible_become_pass=nos3123!
host3 ansible_host=192.168.100.5 ansible_user=nos3 ansible_ssh_pass=nos3123! ansible_become_pass=nos3123!
host4 ansible_host=192.168.100.42 ansible_user=nos3 ansible_ssh_pass=nos3123! ansible_become_pass=nos3123!
