# INIT Mission 
# Activate telemetry
cmd("CFS TO_ENABLE_OUTPUT with DEST_IP '127.0.0.1', DEST_PORT 5011")
wait(3)
# Activate Sensors
cmd("NOVATEL_OEM615 NOVATEL_OEM615_ENABLE_CC")
wait(1)
cmd("GENERIC_TORQUER GENERIC_TORQUER_ENABLE_CC")
wait(1)
cmd("GENERIC_MAG GENERIC_MAG_ENABLE_CC")
wait(1)
cmd("GENERIC_IMU GENERIC_IMU_ENABLE_CC")
wait(1)
cmd("GENERIC_CSS GENERIC_CSS_ENABLE_CC")
wait(1)
cmd("GENERIC_FSS GENERIC_FSS_ENABLE_CC")
wait(1)
cmd("GENERIC_STAR_TRACKER GENERIC_STAR_TRACKER_ENABLE_CC")
wait(1)
cmd("GENERIC_ADCS GENERIC_ADCS_SET_MOMENTUM_MANAGEMENT_CC with GNC_MODE 'ON'")
wait(1)
cmd("GENERIC_ADCS GENERIC_ADCS_SET_MODE_CC with GNC_MODE 'NORMAL_MODE', MAC '1234'")



















